### PR TITLE
Add social sharing doc first pass

### PR DESCRIPTION
**Pull request by justinslack**

### CODE REVIEW

**Comment by justinslack** [comment]
Just adding this for later

**Comment by SteveBarnett** [comment]
@justinslack Added a few starter things. Whatchareckon?

**Comment by justinslack** [comment]
This looks great. Have a few things to add. Will do so shortly.

**Comment by SteveBarnett** [comment]
@justinslack Yay, thanks! I think once you've added a little bit more stuff, we should toot about it from the CTFEDs account?

**Pull request merged**
